### ISSUE TITLE
Sleep/Wake Up problem [Nano USB wifi tplink tl-wn725n]

### ISSUE THREAD

**Issue by indraAsLesmana** [the-braveknight/Lenovo-Z50-DSDT-Patch#3]
thanks for share this great DSDT.
i follow your guide in tonymacs, and work 100% in my Lenovo z40-70, with intel i5 4210u.
but i dont replace the wifi module, its hard for me to buy from another country. i used wifi dogle tplink wn725n v.2 the problem come if i sleep with dogle attach, my laptop still work with screen sleep. and i must force shutdown always for this problem.

can you guide me to fix, this problem? 
thanks..

**Comment by the-braveknight** [comment]
It is a known issue, USB Wi-Fi is not recommended, its kexts tend to cause system instability  especially with sleep.
