### ISSUE TITLE
Problem the latest update Oct-8

### ISSUE THREAD

**Issue by indraAsLesmana** [the-braveknight/Lenovo-Z50-DSDT-Patch#5]
Lenovo z40-70.

after update Oct-8 :
-Trackpad Not found.
-PrtSc (Print Screen), not working.

i must back to Sept-26 build, to get working Trackpad and Print Screen.

**Comment by indraAsLesmana** [comment]
Fix with this 👍 
./install_downloads.sh elan

i dont know, now have a option for this. thaks...

**Comment by the-braveknight** [comment]
Since not all Z50-70 machines come with ELAN trackpads, I decided to let the scripts install the better/open-souce PS2 kext (written by RehabMan) by default... ELAN kext is problematic and tends to mess up with SysPrefs and hide certain options...
