### ISSUE TITLE
Lenovo z40 brightness button not work.

### ISSUE THREAD

**Issue by indraAsLesmana** [the-braveknight/Lenovo-Z50-DSDT-Patch#6]
i install update, this repo with command:
./install_downloads.sh elan

all work perpectly brightness to, except brightness button not work (F11 - F12).
i must go to Sys-Pref for change Brightness.

Thanks...

**Comment by the-braveknight** [comment]
What version of macOS/OS X are you using?
I am aware of this issue, the problem might the problematic ELAN kext that's not handling the requests well enough... We're stuck with this closed-source kext until someone decides to write an open-source kext for ELAN trackpads...
Booting Windows then OS X tends to fix the problem though...

**Comment by indraAsLesmana** [comment]
thanks for your reply Zaid, im using OSX 10.11.6  and as always if i get a problem im back to your Build at Sept -26, and fix my button Brightness issue. but after that im back to yours latest build Oct - 8 install again, and issue gone with latest repo your build.  
![screen shot 2016-10-08 at 4 33 59 pm](https://cloud.githubusercontent.com/assets/12571554/19212117/10348d52-8d75-11e6-9cc3-094f32a5be2e.png)

**Comment by the-braveknight** [comment]
It's probably because I removed the part of code that checks for the touchpad version and returns the request accordingly, that's because my trackpad version is ELAN and I like to use RehabMan's Synaptics driver (for keyboard), which my ELAN kext is not compatible with, so now it's returning 2 values which might be causing the problem... I'll re-add that part of code.

**Comment by the-braveknight** [comment]
I pushed the update, you can run the 'make', 'make install' again.

**Comment by indraAsLesmana** [comment]
my trackpad is ELAN to... "make install" of course im do that.. after this  command "./install_download.sh elan"  as your guide.
thaks my problem Fixed, now with yours latest build.
