### ISSUE TITLE
Right Space/Full Screen apps switch Not Working

### ISSUE THREAD

**Issue by abdullah-abunada** [the-braveknight/Lenovo-Z50-DSDT-Patch#7]
Hi,
Thank you for your amazing effort, I want to report this bug, I have Elan touchpad when I'm trying to switch between fullscreen apps just one direction work and when I want to go back it didn't work.
can you help me to solve this problem.

best,

**Comment by the-braveknight** [comment]
Bugs with the ELAN kext should be reported to the ELAN kext author. I'm sorry but there is nothing anyone can do here as it is closed-source.
