### ISSUE TITLE
Fix Safari freezes

### ISSUE THREAD

**Issue by h1royuki** [the-braveknight/Lenovo-Z50-DSDT-Patch#8]
Hey, maybe need add fix for Safari freezes? Need add [IntelGraphicsFixup](https://sourceforge.net/projects/intelgraphicsfixup/) and [Lilu](https://github.com/vit9696/Lilu/releases) kexts in /System/Library/Extensions/. This fix stably and  works for HD4400.

**Comment by the-braveknight** [comment]
Read here for more info on fixing the Safari+HD4400 issue. https://www.tonymacx86.com/forums/sierra-laptop-support.188/

No interest to test any kexts without documentation.

**Comment by h1royuki** [comment]
It's clear :pensive:
