### ISSUE TITLE
Is this stable to use?

### ISSUE THREAD

**Issue by VienDinhCom** [the-braveknight/Lenovo-Z50-DSDT-Patch#9]
Hi guys,

I am a Lenovo Z50-70 user and I want to install OSX on it. So, is this stable to use? And, can you create release versions for us?

Thanks!

**Comment by the-braveknight** [comment]
It's as perfect as it can possibly be.
 
Follow the guide: 
https://www.tonymacx86.com/threads/guide-lenovo-z50-70-z40-70-using-clover-uefi-10-11.179520/

**Comment by VienDinhCom** [comment]
Ok, thank you :smile:
